apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: rajiyyah/nodeapp:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            scheme: HTTP
            path: /ready
            httpHeaders:
            - name: Host
              value: nodejsapp.com
            port: 3000